import {describe,it,expect,vi} from 'vitest';
import {TranslationManager} from '../src/services/translation/translation-manager.js';
import type {MultiTranslationRequest,ProviderName,TranslationProvider,TranslationResult} from '../src/services/translation/translation-types.js';
const targets=['ar','fr','de','es','it','pt-BR','ja','ko','zh-CN','ru','tr','nl','pl','hi','el'];
const env:any={MAX_TRANSLATION_CONCURRENCY:5,TRANSLATION_TIMEOUT_MS:100,GEMINI_TIMEOUT_MS:50,GROQ_TIMEOUT_MS:50,GOOGLE_TRANSLATE_TIMEOUT_MS:50,GEMINI_COOLDOWN_SECONDS:1,MAX_TARGET_LANGUAGES:15,MAX_TRANSLATION_BATCH_SIZE:15};
function cache(seed:TranslationResult[]=[]){const data=new Map(seed.map(x=>[x.targetLanguage,x]));return{key:(r:any)=>r.targetLanguage,get:vi.fn(async(r:any)=>data.get(r.targetLanguage)??null),set:vi.fn(async(_r:any,value:TranslationResult)=>{data.set(value.targetLanguage,value);})};}
function batch(name:ProviderName,produce:(targets:string[])=>string[]=x=>x):TranslationProvider&{translateMany:ReturnType<typeof vi.fn>}{const translateMany=vi.fn(async(r:MultiTranslationRequest)=>({translations:new Map(produce(r.targetLanguages).map(code=>[code,{text:`${name}-${code}`,targetLanguage:code,latencyMs:1}])),sourceLanguage:'en',requestCount:name==='google'?r.targetLanguages.length:1}));return{name,isConfigured:()=>true,translateMany};}
function failed(name:ProviderName){const translateMany=vi.fn(async()=>{throw new Error('temporary provider failure');});return{name,isConfigured:()=>true,translateMany} as TranslationProvider&{translateMany:ReturnType<typeof vi.fn>};}
describe('batched provider fallback',()=>{it('translates 15 languages with exactly one Gemini request',async()=>{const gemini=batch('gemini'),groq=batch('groq'),google=batch('google'),m=new TranslationManager([gemini,groq,google],cache() as any,env);const result=await m.translateMany({text:'Good morning',targetLanguages:targets});expect(result.translations.size).toBe(15);expect(gemini.translateMany).toHaveBeenCalledTimes(1);expect(gemini.translateMany.mock.calls[0]![0].targetLanguages).toEqual(targets);expect(groq.translateMany).not.toHaveBeenCalled();expect(google.translateMany).not.toHaveBeenCalled();expect(result.providerRequests).toEqual({gemini:1,groq:0,google:0});});
it('makes one Gemini and one Groq request after complete Gemini failure',async()=>{const gemini=failed('gemini'),groq=batch('groq'),google=batch('google'),m=new TranslationManager([gemini,groq,google],cache() as any,env);const result=await m.translateMany({text:'Hello',targetLanguages:targets});expect(result.translations.size).toBe(15);expect(gemini.translateMany).toHaveBeenCalledTimes(1);expect(groq.translateMany).toHaveBeenCalledTimes(1);expect(google.translateMany).not.toHaveBeenCalled();});
it('sends only Gemini missing languages to Groq',async()=>{const gemini=batch('gemini',x=>x.slice(0,13)),groq=batch('groq'),google=batch('google'),m=new TranslationManager([gemini,groq,google],cache() as any,env);const result=await m.translateMany({text:'Hello',targetLanguages:targets});expect(result.translations.size).toBe(15);expect(gemini.translateMany).toHaveBeenCalledTimes(1);expect(groq.translateMany).toHaveBeenCalledTimes(1);expect(groq.translateMany.mock.calls[0]![0].targetLanguages).toEqual(targets.slice(13));expect(google.translateMany).not.toHaveBeenCalled();});
it('sends Google only the final remainder after two partial batches',async()=>{const gemini=batch('gemini',x=>x.slice(0,13)),groq=batch('groq',x=>x.slice(0,1)),google=batch('google'),m=new TranslationManager([gemini,groq,google],cache() as any,env);const result=await m.translateMany({text:'Hello',targetLanguages:targets});expect(result.translations.size).toBe(15);expect(gemini.translateMany).toHaveBeenCalledTimes(1);expect(groq.translateMany).toHaveBeenCalledTimes(1);expect(google.translateMany).toHaveBeenCalledTimes(1);expect(google.translateMany.mock.calls[0]![0].targetLanguages).toEqual([targets[14]]);expect(result.providerRequests).toEqual({gemini:1,groq:1,google:1});});
it('checks every target cache and batches only the five misses',async()=>{const seeded=targets.slice(0,10).map(targetLanguage=>({translatedText:`cached-${targetLanguage}`,targetLanguage,provider:'gemini' as const,latencyMs:0,fallbackDepth:0,cached:true})),gemini=batch('gemini'),m=new TranslationManager([gemini],cache(seeded) as any,env);const result=await m.translateMany({text:'Hello',targetLanguages:targets});expect(result.translations.size).toBe(15);expect(gemini.translateMany).toHaveBeenCalledTimes(1);expect(gemini.translateMany.mock.calls[0]![0].targetLanguages).toEqual(targets.slice(10));});
it('skips a provider already in circuit-breaker cooldown',async()=>{const gemini=batch('gemini'),groq=batch('groq'),m=new TranslationManager([gemini,groq],cache() as any,env);m.health.failure('gemini');m.health.failure('gemini');m.health.failure('gemini');await m.translateMany({text:'Hello',targetLanguages:['ar']});expect(gemini.translateMany).not.toHaveBeenCalled();expect(groq.translateMany).toHaveBeenCalledTimes(1);});
it('does not retry a timed-out provider before immediate fallback',async()=>{const translateMany=vi.fn(()=>new Promise<any>(()=>{})),gemini={name:'gemini' as const,isConfigured:()=>true,translateMany},groq=batch('groq'),m=new TranslationManager([gemini,groq],cache() as any,env);await m.translateMany({text:'Hello',targetLanguages:['ar','fr']});expect(translateMany).toHaveBeenCalledTimes(1);expect(groq.translateMany).toHaveBeenCalledTimes(1);});});
