import { WebhookClient,type Message } from 'discord.js';
import type { PrismaClient } from '@prisma/client';
import { logger } from '../../utils/logger.js';
import type { SettingsCache } from './settings-cache.js';
export type TranslationStyle='S1'|'S1B'|'S2'|'S3'|'S4'|'S5'|'S6'|'S6B'|'S7'|'S8'|'S9';
export function resolveEffectiveStyle(channelStyle:string|null|undefined,guildStyle:string|null|undefined,configuredDefault:TranslationStyle='S9'):TranslationStyle{const value=channelStyle??guildStyle??configuredDefault;return /^S(?:1B?|2|3|4|5|6B?|7|8|9)$/.test(value)?value as TranslationStyle:configuredDefault;}
type WebhookLike={send(options:any):Promise<any>;editMessage?(id:string,options:any):Promise<any>};
type RenderInput={destination:any;source:Message;content:string;style:TranslationStyle;sameChannel:boolean};
export class TranslationOutputRenderer {
  private webhookClients=new Map<string,WebhookLike>();
  constructor(private db:PrismaClient,private webhookFactory:(credentials:{id:string;token:string})=>WebhookLike=credentials=>new WebhookClient(credentials),private settingsCache?:SettingsCache){}
  private async createWebhook(channel:any){try{const hook=await channel.createWebhook({name:'Storm Translator',reason:'Managed S9 translation output'});if(!hook.token)throw new Error('Discord did not return a webhook token');const row=await this.db.managedWebhook.upsert({where:{channelId:channel.id},create:{channelId:channel.id,guildId:channel.guild.id,webhookId:hook.id,token:hook.token},update:{webhookId:hook.id,token:hook.token,guildId:channel.guild.id}});if(this.settingsCache)this.settingsCache.invalidateWebhook(channel.id);const client=this.webhookFactory({id:row.webhookId,token:row.token});this.webhookClients.set(channel.id,client);return client;}catch(e){logger.error({channelId:channel.id,error:e instanceof Error?e.message:'unknown'},'Cannot create managed translation webhook; verify Manage Webhooks permission');throw new Error('S9 webhook output requires Manage Webhooks permission in the destination channel.');}}
  private async webhook(channel:any){const cachedClient=this.webhookClients.get(channel.id);if(cachedClient)return cachedClient;const row=this.settingsCache?await this.settingsCache.getManagedWebhook(channel.id):await this.db.managedWebhook.findUnique({where:{channelId:channel.id}});if(row){const client=this.webhookFactory({id:row.webhookId,token:row.token});this.webhookClients.set(channel.id,client);return client;}return this.createWebhook(channel);}
  private identity(source:Message){return{username:source.member?.displayName??source.author.globalName??source.author.username,avatarURL:source.member?.displayAvatarURL({size:128})??source.author.displayAvatarURL({size:128})};}
  private async replyHeader(source:Message,destinationId:string){if(!source.reference?.messageId)return'';const mapping=await this.db.translatedMessage.findFirst({where:{originalMessageId:source.reference.messageId,translatedChannelId:destinationId,partIndex:0}}),url=mapping?`https://discord.com/channels/${source.guildId}/${destinationId}/${mapping.translatedMessageId}`:`https://discord.com/channels/${source.guildId}/${source.reference.channelId??source.channelId}/${source.reference.messageId}`;let excerpt='Referenced message';try{const referenced=await source.fetchReference();excerpt=referenced.content.replace(/\s+/g,' ').slice(0,120)||excerpt;}catch{/* compact link remains available */}return`> [↩ **REPLY**](${url}) *${excerpt.replace(/[*_`]/g,'\\$&')}*\n`;}
  private format(style:TranslationStyle,content:string){switch(style){case'S1':case'S1B':case'S2':case'S3':case'S4':return`> Translation\n${content}`;case'S6':case'S6B':return content.replace(/\s*\n\s*/g,' ');case'S7':return`**Translation**\n${content}`;case'S8':return`>>> ${content}`;default:return content;}}
  async send(input:RenderInput){if(input.style!=='S9'){const payload={content:this.format(input.style,input.content),allowedMentions:{parse:[] as never[],repliedUser:false}};return input.sameChannel?input.source.reply(payload):input.destination.send(payload);}const header=await this.replyHeader(input.source,input.destination.id),identity=this.identity(input.source),options={content:`${header}${input.content}`,...identity,allowedMentions:{parse:[] as never[]}};let webhook=await this.webhook(input.destination);try{return await webhook.send(options);}catch(first){logger.warn({channelId:input.destination.id,error:first instanceof Error?first.message:'unknown'},'Managed webhook send failed; recreating once');this.webhookClients.delete(input.destination.id);if(this.settingsCache)this.settingsCache.invalidateWebhook(input.destination.id);await this.db.managedWebhook.deleteMany({where:{channelId:input.destination.id}});webhook=await this.createWebhook(input.destination);return webhook.send(options);}}
  async edit(channel:any,messageId:string,content:string){const cachedClient=this.webhookClients.get(channel.id);if(cachedClient?.editMessage)return cachedClient.editMessage(messageId,{content,allowedMentions:{parse:[]}});const row=this.settingsCache?await this.settingsCache.getManagedWebhook(channel.id):await this.db.managedWebhook.findUnique({where:{channelId:channel.id}});if(row){const webhook=this.webhookFactory({id:row.webhookId,token:row.token});this.webhookClients.set(channel.id,webhook);if(webhook.editMessage)return webhook.editMessage(messageId,{content,allowedMentions:{parse:[]}});}const message=await channel.messages.fetch(messageId);return message.edit({content,allowedMentions:{parse:[]}});}
}
